### ISSUE TITLE
画のキャンセル問題

### ISSUE THREAD

**Issue by 8810KMKM** [taigakiyokawa/otokomeshi#30]
1. 新規投稿から画像を選択する

2. 別の画像を選択しようとしたけど、やっぱりやめる (キャンセルを押す)

3. 1.で選択した画像が選択されていない状態になる

4. そのまま投稿するとエラー（画像: meshimはnot null制約）

**Comment by taigakiyokawa** [comment]
キャンセル押されたらデフォルト画像に変更する的な感じで一応
