### ISSUE TITLE
postのmeshimはjsonじゃなくてもいいかも

### ISSUE THREAD

**Issue by 8810KMKM** [taigakiyokawa/otokomeshi#57]
参考にした方法が２つあって、最初の方法でjsonにしたものをそのまま2つ目の方法でも使っていた。
でもstringでもいける（userのuser_img）ので stringに変更してもいいかも。

てかちゃんと方法変える時点でブランチ切ってればよかった。。。

**Comment by taigakiyokawa** [comment]
なんかseeds.rbも生成できたし今の所問題ないからそのままにしときます

**Comment by 8810KMKM** [comment]
okです
